version: '2'
services:
  web_app:
    image: itsjeff/docker-php7.2:latest
    container_name: web_app
    volumes:
      - .:/var/www/html
      - ./nginx/default:/etc/nginx/sites-enabled/default
    environment:
      - VIRTUAL_HOST=local.demo.com
      - VIRTUAL_PORT=80
    extra_hosts:
      - "local.demo.com.:127.0.0.1"
    network_mode: "bridge"
