version: '3.7'

networks:
  web:
    external: true

  demo-com-network:
    internal: true

services:
  demo_com_web:
    image: itsjeff/dev-php:latest
    container_name: demo_com_web
    volumes:
      - .:/var/www/html
      - ./environment/nginx/default:/etc/nginx/sites-enabled/default
    env_file:
      - .docker.env
    links:
      - demo_com_db
      - demo_com_redis
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.demo_com_web.rule=Host(`local.demo.com`)
      - traefik.http.routers.demo_com_web.entrypoints=web
    networks:
      - demo-com-network
      - web

  demo_com_redis:
    image: redis
    container_name: demo_com_redis
    volumes:
      - ./environment/redis:/data
    network_mode: "bridge"

  demo_com_db:
    image: mysql:5.7
    container_name: demo_com_db
    command: "--default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0"
    volumes:
      - ./environment/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
    networks:
      - demo-com-network
      - web
