version: '2'
services:
  app_web:
    image: itsjeff/docker-php7.2:latest
    container_name: app_web
    volumes:
      - .:/var/www/html
      - ./nginx/default:/etc/nginx/sites-enabled/default
    environment:
      - VIRTUAL_HOST=local.demo.com
      - VIRTUAL_PORT=80
    extra_hosts:
      - "local.demo.com.:127.0.0.1"
    links:
      - app_redis
    network_mode: "bridge"
  app_redis:
    image: redis
    container_name: app_redis
    volumes:
      - ./redis:/data
    network_mode: "bridge"