version: '2'
services:
  app_web:
    image: itsjeff/dev-php:latest
    container_name: app_web
    volumes:
      - .:/var/www/html
      - ./environment/nginx/default:/etc/nginx/sites-enabled/default
    environment:
      - VIRTUAL_HOST=local.demo.com
      - VIRTUAL_PORT=80
    env_file: .docker.env
    extra_hosts:
      - "local.demo.com:127.0.0.1"
    links:
      - app_redis
      - app_db
    network_mode: "bridge"
  app_redis:
    image: redis
    container_name: app_redis
    volumes:
      - ./environment/redis:/data
    network_mode: "bridge"
  app_db:
    image: mysql:5.7
    container_name: app_db
    volumes:
      - ./environment/mysql:/var/lib/mysql
    command: "--default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0"
    ports:
      - "3306"
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    network_mode: "bridge"
