version: '3'

networks:
  public:
    external: true

services:
  traefik:
    image: traefik:latest
    container_name: traefik_proxy
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml