defaultEntryPoints = ["web"]
insecureSkipVerify = true

[entryPoints]
  [entryPoints.web]
    address = ":80"

[api]
  insecure = true
  dashboard = true

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  exposedByDefault = false
  network = "public"